# Generated by Django 5.2.7 on 2026-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_home_address_description_user_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker')], max_length=20),
        ),
    ]
