# Generated by Django 5.2.9 on 2026-01-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('general_househelp', 'General Househelp'), ('nanny', 'Nanny'), ('house_cleaner', 'House Cleaner'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('elderly', 'Elderly Care'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker'), ('admin', 'Admin')], default='worker', max_length=20),
        ),
    ]
