# Generated by Django 5.2.9 on 2026-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('less_year', 'Less than a year'), ('1_3yr', '1-3 years'), ('3_5yr', '3-5 years'), ('5plus_yr', 'More than 5 years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_img',
            field=models.ImageField(blank=True, null=True, upload_to='identity/passport/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address_description',
            field=models.TextField(blank=True, help_text='Directions', null=True),
        ),
    ]
