# Generated by Django 5.2.9 on 2026-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_experience_user_passport_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
