# Generated by Django 5.2.9 on 2026-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_expected_salary_user_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='accommodation',
            field=models.CharField(blank=True, choices=[('live_in', 'Live In'), ('live_out', 'Live Out')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
