# Generated by Django 5.2.9 on 2026-01-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_current_employer_user_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='current_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
