# Generated by Django 5.2.9 on 2026-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_booking_current_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_emoji', models.CharField(default='💼', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_new_registrations', models.BooleanField(default=True)),
                ('support_email', models.EmailField(default='support@kykam.com', max_length=254)),
                ('platform_fee_info', models.TextField(default='Free for now!')),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
