# Generated by Django 5.2.9 on 2026-01-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_category_platformsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='worker_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='users.category'),
        ),
    ]
