# Generated by Django 5.2.9 on 2026-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_worker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('general_househelp', 'General Househelp'), ('nanny', 'Nanny'), ('house_cleaner', 'House Cleaner'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('elderly', 'Elderly Care'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
