# Generated by Django 5.2.9 on 2026-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='broadcast_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='platform_fee_info',
            field=models.TextField(default='Kyam keeps it free for now!'),
        ),
    ]
