# Generated by Django 5.2.9 on 2026-01-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_platformsetting_broadcast_message_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('employer', 'worker', 'status'), name='unique_active_booking'),
        ),
    ]
