# Generated by Django 5.2.9 on 2026-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('few months', 'Less than a year'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', 'More than 5 years')], max_length=20, null=True),
        ),
    ]
