# Generated by Django 5.2.1 on 2026-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('general_househelp', 'General Househelp'), ('nanny', 'Nanny'), ('house_cleaner', 'House Cleaner'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('elderly', 'Elderly Care'), ('other', 'Other'), ('driver', 'Driver')], max_length=30, null=True),
        ),
    ]
