# Generated by Django 5.2.9 on 2026-03-29 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_accepted_terms_user_accepted_terms_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Format: 2547XXXXXXXX', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='M-Pesa Receipt Number', max_length=50, null=True, unique=True)),
                ('checkout_request_id', models.CharField(help_text='Unique ID for STK Push request', max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(help_text="What the payment is for, e.g., 'Account Activation'", max_length=100)),
                ('raw_callback_data', models.JSONField(blank=True, help_text='Full JSON payload from M-Pesa', null=True)),
                ('result_desc', models.TextField(blank=True, help_text='Description of the result/error from M-Pesa', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['checkout_request_id'], name='users_payme_checkou_05a603_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='users_payme_transac_0d1f67_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['phone_number'], name='users_payme_phone_n_f36377_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='users_payme_status_16df18_idx'),
        ),
    ]
