# Generated by Django 5.2.9 on 2026-04-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_payment_user_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number used to make the M-Pesa payment', max_length=20)),
                ('mpesa_transaction_code', models.CharField(help_text='M-Pesa transaction/receipt code e.g. SLK4H7R2T0', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=99, max_digits=10)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_verification', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mpesa_transaction_code'], name='users_manua_mpesa_t_74eca7_idx'), models.Index(fields=['status'], name='users_manua_status_17d670_idx')],
            },
        ),
    ]
