# Generated by Django 5.2.9 on 2026-04-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_manualpaymentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('temporary_access', 'Temporary Access'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unpaid', max_length=20),
        ),
    ]
