# Generated by Django 5.2.9 on 2026-04-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_payment_submitted_at_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unpaid', max_length=20),
        ),
    ]
