# Generated by Django 5.2.9 on 2026-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
